evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:    /

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /

paiment:
    resource: "@PaimentBundle/Resources/config/routing.yml"
    prefix:   /

recrutement:
    resource: "@RecrutementBundle/Resources/config/routing.yml"
    prefix:   /

marketing:
    resource: "@MarketingBundle/Resources/config/routing.yml"
    prefix:   /

profil:
    resource: "@ProfilBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /


app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"