<?php

namespace ProfilBundle\Repository;

/**
 * CertifcationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CertifcationRepository extends \Doctrine\ORM\EntityRepository
{
}
