<?php

namespace ProfilBundle\Repository;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{
    public function countrate($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT AVG(r.avis) FROM ProfilBundle:Rate r WHERE r.iduser_rated=:id')
            ->setParameter('id',$id)

            ->getResult();
    }
}
